# Generated by Django 5.2.14 on 2026-05-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_markdown', models.TextField()),
                ('mood_tag', models.CharField(blank=True, max_length=64)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('skipped', 'Skipped (no API key)'), ('error', 'Error')], default='pending', max_length=32)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.journalentry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'unique_together': {('person', 'entry')},
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='persons',
            field=models.ManyToManyField(related_name='entries', through='entries.PersonJournalEntry', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', '-created_at'], name='entries_jou_owner_i_21ac27_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', 'extraction_status'], name='entries_jou_owner_i_35dc2f_idx'),
        ),
    ]
