# Generated by Django 5.2.14 on 2026-05-31 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
            options={
                'unique_together': {('organization', 'entry')},
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='organizations',
            field=models.ManyToManyField(related_name='entries', through='entries.OrganizationJournalEntry', to='orgs.organization'),
        ),
    ]
