# Generated by Django 5.2.14 on 2026-06-16 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.TextField(blank=True, default='')),
                ('build_status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('build_log', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.TextField()),
                ('narration_text', models.TextField(blank=True, default='')),
                ('narration_generated', models.BooleanField(default=False)),
                ('audio_file', models.TextField(blank=True, default='')),
                ('target_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('next_scheduled_date', models.DateField(blank=True, null=True)),
                ('last_prayed_at', models.DateField(blank=True, null=True)),
                ('answered_date', models.DateField(blank=True, null=True)),
                ('answer_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_topics', to='groups.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_topics', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_topics', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayed_on', models.DateField()),
                ('answered', models.BooleanField(default=False)),
                ('answer_note', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prayer.prayersession')),
                ('prayer_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prayer.prayertopic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prayersession',
            constraint=models.UniqueConstraint(fields=('owner', 'session_date'), name='unique_session_per_owner_date'),
        ),
        migrations.AddIndex(
            model_name='prayertopic',
            index=models.Index(fields=['owner', 'answered_date'], name='prayer_pray_owner_i_bc84d5_idx'),
        ),
        migrations.AddIndex(
            model_name='prayertopic',
            index=models.Index(fields=['owner', 'target_frequency', 'next_scheduled_date'], name='prayer_pray_owner_i_baeed3_idx'),
        ),
        migrations.AddConstraint(
            model_name='prayerlog',
            constraint=models.UniqueConstraint(fields=('session', 'prayer_topic'), name='unique_log_per_session_topic'),
        ),
    ]
