# Generated by Django 5.2.14 on 2026-05-31 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_birthday_person_deceased_at_person_life_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('inverse_name', models.CharField(max_length=64)),
                ('is_symmetric', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('love', 'Love'), ('family', 'Family'), ('friend', 'Friend'), ('work', 'Work'), ('ministry', 'Ministry'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('system', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paired_id', models.IntegerField(blank=True, null=True)),
                ('association_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='associations.associationtype')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_from', to='people.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_associations', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_to', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'from_person'], name='association_owner_i_862877_idx'), models.Index(fields=['owner', 'to_person'], name='association_owner_i_747d4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'from_person', 'to_person', 'association_type'), name='unique_association_row')],
            },
        ),
    ]
