# Generated by Django 5.2.14 on 2026-05-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('data_type_hint', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('enum', 'Enum'), ('url', 'URL')], default='text', max_length=16)),
                ('first_proposed_at', models.DateTimeField(auto_now_add=True)),
                ('ai_confidence_on_creation', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('merged', 'Merged')], default='active', max_length=16)),
                ('usage_count', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('first_proposed_from_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_property_defs', to='entries.journalentry')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='properties.propertydef')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_defs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField()),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending_review', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_properties', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='people.person')),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_properties', to='entries.journalentry')),
                ('property_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='properties.propertydef')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertydef',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_c1458d_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertydef',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_property_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='personproperty',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_830e49_idx'),
        ),
        migrations.AddIndex(
            model_name='personproperty',
            index=models.Index(fields=['person', 'property_def'], name='properties__person__5f9c0d_idx'),
        ),
    ]
