# Generated by Django 5.2.14 on 2026-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_seed_standard_property_defs'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpropertydef',
            name='topic',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='propertydef',
            name='topic',
            field=models.CharField(default='other', max_length=32),
        ),
    ]
