# Generated by Django 5.2.14 on 2026-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDay',
            fields=[
                ('guid', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('passage_reference', models.TextField(blank=True, default='')),
                ('commentary', models.TextField(blank=True, default='')),
                ('ot_reference', models.TextField(blank=True, default='')),
                ('ot_link', models.URLField(blank=True, default='')),
                ('nt_reference', models.TextField(blank=True, default='')),
                ('nt_link', models.URLField(blank=True, default='')),
                ('esv_day_audio_url', models.URLField(blank=True, default='')),
                ('esv_day_audio_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('esv_org_audio_url', models.URLField(blank=True, default='')),
                ('esv_ot_html', models.TextField(blank=True, default='')),
                ('esv_ot_text', models.TextField(blank=True, default='')),
                ('esv_nt_html', models.TextField(blank=True, default='')),
                ('esv_nt_text', models.TextField(blank=True, default='')),
                ('raw_content_html', models.TextField(blank=True, default='')),
                ('audio_cached_path', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
