# Generated by Django 5.2.14 on 2026-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingday',
            name='intro_narration_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
