# Generated by Django 5.2.14 on 2026-06-01 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0002_organizationjournalentry_journalentry_organizations'),
        ('people', '0003_historicalperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('life_stage', models.CharField(blank=True, default='', max_length=16)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('proposal_payload', models.JSONField(blank=True, default=dict)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('created', 'Created'), ('rejected', 'Rejected')], default='pending_review', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_persons', to=settings.AUTH_USER_MODEL)),
                ('resolved_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_from', to='people.person')),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_persons', to='entries.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='extraction__owner_i_773133_idx')],
            },
        ),
    ]
