# Generated by Django 5.2.14 on 2026-05-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('none', 'None')], default='none', max_length=16)),
                ('last_prayed_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_schedules', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_schedule', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'next_due_at'], name='future_pray_owner_i_dbd084_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('person_property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_memo', to='properties.personproperty')),
            ],
            options={
                'indexes': [models.Index(fields=['due_at'], name='future_revi_due_at_fdcd2a_idx')],
            },
        ),
    ]
