# Generated by Django 5.2.14 on 2026-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmemo',
            name='suspended',
            field=models.BooleanField(default=False, help_text='When true, card is removed from the active review deck.'),
        ),
    ]
