# Generated by Django 5.2.14 on 2026-05-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('relationship_category', models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('bridge_student', 'Bridge student'), ('other', 'Other')], default='other', max_length=32)),
                ('notes_markdown', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['owner', 'archived'], name='people_pers_owner_i_fa93a5_idx'), models.Index(fields=['owner', 'relationship_category'], name='people_pers_owner_i_deeb31_idx')],
            },
        ),
    ]
