"""Reconcile a legacy v0.1 people schema with the v2 model.

Production's database still has the v0.1 ``people_person`` table (full_name,
relationship_category, notes_markdown, …) because the original people.0001 was
already recorded as applied there — so the rewritten v2 people.0001 never ran
against it, and ``people_child`` was never created.

This migration patches that legacy Postgres schema in place: it adds the v2
columns, copies ``full_name`` into ``name`` so existing people are preserved,
drops the obsolete columns/indexes, and creates ``people_child``.

On any fresh database (new deploys, the SQLite test DB) people.0001 already
produced the correct v2 schema, so this migration detects that and is a no-op.
It only touches PostgreSQL databases that still carry the legacy columns.
"""
from django.db import migrations


LEGACY_PATCH_SQL = """
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS name varchar(255);
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS career text NOT NULL DEFAULT '';
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS school text NOT NULL DEFAULT '';
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS major text NOT NULL DEFAULT '';
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS partner_name text NOT NULL DEFAULT '';
ALTER TABLE people_person ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';

UPDATE people_person
SET name = COALESCE(NULLIF(full_name, ''), 'Unnamed')
WHERE name IS NULL;

ALTER TABLE people_person ALTER COLUMN name SET NOT NULL;

UPDATE people_person
SET life_stage = 'adult'
WHERE life_stage IS NULL
   OR life_stage NOT IN ('student', 'single', 'married', 'adult');

ALTER TABLE people_person ALTER COLUMN life_stage SET DEFAULT 'adult';
ALTER TABLE people_person ALTER COLUMN life_stage SET NOT NULL;

ALTER TABLE people_person DROP COLUMN IF EXISTS full_name;
ALTER TABLE people_person DROP COLUMN IF EXISTS preferred_name;
ALTER TABLE people_person DROP COLUMN IF EXISTS relationship_category;
ALTER TABLE people_person DROP COLUMN IF EXISTS notes_markdown;
ALTER TABLE people_person DROP COLUMN IF EXISTS archived;
ALTER TABLE people_person DROP COLUMN IF EXISTS birthday;
ALTER TABLE people_person DROP COLUMN IF EXISTS deceased_at;

DROP INDEX IF EXISTS people_pers_owner_i_fa93a5_idx;
DROP INDEX IF EXISTS people_pers_owner_i_deeb31_idx;
DROP INDEX IF EXISTS people_pers_owner_i_540ccf_idx;
CREATE INDEX IF NOT EXISTS people_pers_owner_i_c2093e_idx
    ON people_person (owner_id, name);

DROP TABLE IF EXISTS people_historicalperson CASCADE;

CREATE TABLE IF NOT EXISTS people_child (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    birthdate date NULL,
    birth_year integer NULL CHECK (birth_year >= 0),
    person_id bigint NOT NULL
        REFERENCES people_person (id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS people_child_person_id_idx
    ON people_child (person_id);
"""


def align_legacy_schema(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = 'people_person' AND column_name = 'full_name'"
        )
        is_legacy = cursor.fetchone() is not None

    if not is_legacy:
        return

    with connection.cursor() as cursor:
        cursor.execute(LEGACY_PATCH_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(align_legacy_schema, migrations.RunPython.noop),
    ]
