"""Reconcile a legacy v0.1 people schema with the v2 model.

Production's database still has the v0.1 ``people_person`` table (full_name,
relationship_category, notes_markdown, …) because the original people.0001 was
already recorded as applied there — so the rewritten v2 people.0001 never ran
against it, and ``people_child`` was never created.

This migration patches that legacy Postgres schema in place: it adds the v2
columns, copies ``full_name`` into ``name`` so existing people are preserved,
drops the obsolete columns/indexes, and creates ``people_child``.

On any fresh database (new deploys, the SQLite test DB) people.0001 already
produced the correct v2 schema, so every statement here is guarded with
``IF [NOT] EXISTS`` and becomes a harmless no-op.

The migration is non-atomic and runs each statement in its own transaction:
``people_person`` is referenced by deferrable foreign keys (prayer, groups), so
mixing an ``UPDATE`` and ``ALTER TABLE`` in a single transaction raises
"cannot ALTER TABLE because it has pending trigger events". Running each
statement separately avoids that, and the idempotent guards make a retry safe.
"""
from django.db import migrations


# Each statement is idempotent and executed in its own autocommit transaction.
SCHEMA_STATEMENTS = [
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS name varchar(255)",
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS career text NOT NULL DEFAULT ''",
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS school text NOT NULL DEFAULT ''",
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS major text NOT NULL DEFAULT ''",
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS partner_name text NOT NULL DEFAULT ''",
    "ALTER TABLE people_person ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT ''",
]

POST_BACKFILL_STATEMENTS = [
    "UPDATE people_person SET name = 'Unnamed' WHERE name IS NULL OR name = ''",
    "ALTER TABLE people_person ALTER COLUMN name SET NOT NULL",
    "UPDATE people_person SET life_stage = 'adult' "
    "WHERE life_stage IS NULL OR life_stage NOT IN ('student', 'single', 'married', 'adult')",
    "ALTER TABLE people_person ALTER COLUMN life_stage SET DEFAULT 'adult'",
    "ALTER TABLE people_person ALTER COLUMN life_stage SET NOT NULL",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS full_name",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS preferred_name",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS relationship_category",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS notes_markdown",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS archived",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS birthday",
    "ALTER TABLE people_person DROP COLUMN IF EXISTS deceased_at",
    "DROP INDEX IF EXISTS people_pers_owner_i_fa93a5_idx",
    "DROP INDEX IF EXISTS people_pers_owner_i_deeb31_idx",
    "DROP INDEX IF EXISTS people_pers_owner_i_540ccf_idx",
    "CREATE INDEX IF NOT EXISTS people_pers_owner_i_c2093e_idx ON people_person (owner_id, name)",
    "DROP TABLE IF EXISTS people_historicalperson CASCADE",
    "CREATE TABLE IF NOT EXISTS people_child ("
    " id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
    " name varchar(255) NOT NULL,"
    " birthdate date NULL,"
    " birth_year integer NULL CHECK (birth_year >= 0),"
    " person_id bigint NOT NULL REFERENCES people_person (id) DEFERRABLE INITIALLY DEFERRED"
    ")",
    "CREATE INDEX IF NOT EXISTS people_child_person_id_idx ON people_child (person_id)",
]


def _column_exists(cursor, table, column):
    cursor.execute(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = %s AND column_name = %s",
        [table, column],
    )
    return cursor.fetchone() is not None


def align_legacy_schema(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    def run(sql):
        with connection.cursor() as cursor:
            cursor.execute(sql)

    for statement in SCHEMA_STATEMENTS:
        run(statement)

    # Preserve existing people: copy the legacy full_name into the new name
    # column before full_name is dropped. Guarded so a retry (after full_name
    # is already gone) skips cleanly.
    with connection.cursor() as cursor:
        has_full_name = _column_exists(cursor, "people_person", "full_name")
    if has_full_name:
        run(
            "UPDATE people_person SET name = COALESCE(NULLIF(full_name, ''), 'Unnamed') "
            "WHERE name IS NULL OR name = ''"
        )

    for statement in POST_BACKFILL_STATEMENTS:
        run(statement)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(align_legacy_schema, migrations.RunPython.noop),
    ]
