# Generated by Django 5.2.14 on 2026-05-31 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deceased_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('infant', 'Infant (0–1)'), ('toddler', 'Toddler (1–3)'), ('child', 'Child (4–12)'), ('teen', 'Teen (13–17)'), ('young_adult', 'Young adult (18–29)'), ('adult', 'Adult (30–64)'), ('senior', 'Senior (65+)')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='relationship_category',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('work', 'Work'), ('neighbor', 'Neighbor'), ('ministry', 'Ministry'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'life_stage'], name='people_pers_owner_i_540ccf_idx'),
        ),
    ]
