# Generated by Django 5.2.14 on 2026-06-01 01:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_birthday_person_deceased_at_person_life_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('relationship_category', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('work', 'Work'), ('neighbor', 'Neighbor'), ('ministry', 'Ministry'), ('other', 'Other')], default='other', max_length=32)),
                ('life_stage', models.CharField(blank=True, choices=[('infant', 'Infant (0–1)'), ('toddler', 'Toddler (1–3)'), ('child', 'Child (4–12)'), ('teen', 'Teen (13–17)'), ('young_adult', 'Young adult (18–29)'), ('adult', 'Adult (30–64)'), ('senior', 'Senior (65+)')], default='', max_length=16)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deceased_at', models.DateField(blank=True, null=True)),
                ('notes_markdown', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical person',
                'verbose_name_plural': 'historical persons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
