# Generated by Django 5.2.14 on 2026-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_historicalperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='photo_thumbnail_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_thumbnail_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('infant', 'Infant (0–1)'), ('toddler', 'Toddler (1–3)'), ('child', 'Child'), ('teen', 'Teen'), ('young_adult', 'Young adult'), ('adult', 'Adult'), ('senior', 'Senior')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='person',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('infant', 'Infant (0–1)'), ('toddler', 'Toddler (1–3)'), ('child', 'Child'), ('teen', 'Teen'), ('young_adult', 'Young adult'), ('adult', 'Adult'), ('senior', 'Senior')], default='', max_length=16),
        ),
    ]
